use_frameworks!

platform :ios, '10.0'

target 'CalendarPersonModelWare_Example' do
  pod 'CalendarPersonModelWare', :path => '../'

  target 'CalendarPersonModelWare_Tests' do
    inherit! :search_paths

    
  end
end
